import json
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from model.state_based_rostering import QuantumForecast


# -----------------------------------------------------------------------------
# Store mapping & file locations
# -----------------------------------------------------------------------------
STORE_MAP_INPUTS = {
    "Castle Towers": "Mecca Castle Towers",
    "Double Bay": "Mecca Double Bay",
    "Parramatta": "Mecca Parramatta",
}

FORECAST_DATA_FOLDER = "data/forecast/"
FORECAST_DATA_FILE_NAMES = {
    "Castle Towers": "Castle_Towers.json",
    "Double Bay": "Double_Bay.json",
    "Parramatta": "Parramatta.json",
}

# Columns we need from all_stores.xlsx
FORECAST_INPUT_REQUIRED_COLUMNS = [
    "Date",
    "SalesActual",
    "SalesForecast",   # Existing / legacy forecast
    "HoursActual",
    "HoursForecast",
]

# -----------------------------------------------------------------------------
# Calendar & scenario settings
# -----------------------------------------------------------------------------
# Story:
# - Use history up to 31 Aug 2025 to build the initial "baseline" forecast.
# - Forecast from 1 Sep 2025 all the way to 31 Dec 2025.
# - Then each week we add new actuals and re-run the forecast over the SAME horizon.
HISTORY_END_FOR_INITIAL = datetime(2025, 8, 31)            # last day of history for baseline
INITIAL_FORECAST_START = datetime(2025, 9, 1)              # forecast start: 1 Sep 2025
FINAL_FORECAST_DATE = datetime(2025, 12, 31)               # forecast end for all runs

# Weeks for the “weekly reforecast” controls (based on your data cut)
FIRST_WEEK_NUMBER = 36                                     # week of 31 Aug–6 Sep
FIRST_WEEK_START = datetime(2025, 8, 31)                   # Sunday starting week 36
MAX_ACTUAL_WEEK = 43                                       # Week 43 ends 25 Oct 2025


def cleanup_store_forecast_files(store_name: str):
    """
    Delete the baseline/re-forecast JSON files generated by this tab for a store.

    We keep the canonical engine file (e.g. 'Parramatta.json') and only remove:
      - '<Store>_O.json'   -> baseline for this lab
      - '<Store>_W*.json'  -> weekly re-forecasts for this lab
    """
    folder = Path(FORECAST_DATA_FOLDER)
    base_name = FORECAST_DATA_FILE_NAMES[store_name].replace(".json", "")

    patterns = [
        f"{base_name}_O.json",   # baseline for this tab
        f"{base_name}_W*.json",  # weekly re-forecast files
    ]

    for pattern in patterns:
        for path in folder.glob(pattern):
            try:
                path.unlink()
                print(f"[Re-Forecast Lab] Deleted old file: {path}")
            except Exception as e:
                print(f"[Re-Forecast Lab] Could not delete {path}: {e}")


def shrink_metric_cards():
    # Make KPI tiles shorter + smaller text
    st.markdown(
        """
        <style>
        /* Streamlit metric container */
        div[data-testid="metric-container"],
        div[data-testid="stMetric"] {
            padding: 0.35rem 0.6rem !important;   /* less padding */
            border-radius: 0.75rem !important;
            min-height: 0 !important;             /* remove tall min-height */
        }

        /* Metric label (e.g. "Store", "Status") */
        div[data-testid="metric-container"] label,
        div[data-testid="stMetric"] label {
            font-size: 0.70rem !important;        /* smaller label font */
        }

        /* Metric value (e.g. "Parramatta", "Baseline not yet run") */
        div[data-testid="metric-container"] > div:nth-child(2),
        div[data-testid="stMetric"] > div:nth-child(2) {
            font-size: 1.2rem !important;         /* slightly smaller value */
        }
        </style>
        """,
        unsafe_allow_html=True,
    )


# -----------------------------------------------------------------------------
# Helper: turn week number into start and end dates
# -----------------------------------------------------------------------------
def get_week_dates(week_number: int, year: int = 2025):
    """
    Calculate start and end dates for a given week number (Week 36 starts 31 Aug 2025).

    We use Sunday–Saturday weeks so it lines up cleanly with the data in all_stores.
    """
    offset = week_number - FIRST_WEEK_NUMBER
    start_date = FIRST_WEEK_START + timedelta(weeks=offset)
    end_date = start_date + timedelta(days=6)
    return start_date, end_date


# -----------------------------------------------------------------------------
# Optional helpers (not currently exposed in the UI)
# -----------------------------------------------------------------------------
def generate_weekly_template(week_number: int) -> pd.DataFrame:
    """
    Generate a simple 7-day template for a given week.
    Handy if you later decide to allow manual CSV uploads of actuals.
    """
    start_date, end_date = get_week_dates(week_number)
    dates = pd.date_range(start=start_date, end=end_date, freq="D")

    template_df = pd.DataFrame(
        {
            "Date": dates,
            "SalesActual": [45000, 38000, 39000, 41000, 43000, 52000, 48000],
            "HoursActual": [120, 105, 108, 112, 118, 135, 128],
        }
    )
    return template_df


def validate_weekly_data(df: pd.DataFrame, expected_week: int, year: int = 2025):
    """
    Basic validation if you ever wire up manual CSV uploads for weekly actuals.

    Returns:
        (is_valid: bool, message: str, week_start: datetime, week_end: datetime)
    """
    required_columns = ["Date", "SalesActual", "HoursActual"]

    missing_cols = [col for col in required_columns if col not in df.columns]
    if missing_cols:
        return False, f"Missing required columns: {', '.join(missing_cols)}", None, None

    try:
        df["Date"] = pd.to_datetime(df["Date"])
    except Exception as e:
        return False, f"Invalid date format: {str(e)}", None, None

    expected_start, expected_end = get_week_dates(expected_week, year)
    data_start = df["Date"].min()
    data_end = df["Date"].max()

    if data_start.date() != expected_start.date():
        return (
            False,
            f"Data start date {data_start.date()} doesn't match expected week "
            f"{expected_week} start {expected_start.date()}",
            None,
            None,
        )

    if data_end.date() != expected_end.date():
        return (
            False,
            f"Data end date {data_end.date()} doesn't match expected week "
            f"{expected_week} end {expected_end.date()}",
            None,
            None,
        )

    if len(df) != 7:
        return False, f"Expected 7 days of data, got {len(df)}", None, None

    null_counts = df[required_columns].isnull().sum()
    if null_counts.any():
        null_cols = null_counts[null_counts > 0]
        return False, f"Found null values in: {dict(null_cols)}", None, None

    return True, "Valid", expected_start, expected_end


def merge_weekly_data(existing_df: pd.DataFrame, new_weekly_df: pd.DataFrame) -> pd.DataFrame:
    """
    Merge new weekly data with existing historical data (avoid overlapping dates).
    """
    existing_df["Date"] = pd.to_datetime(existing_df["Date"])
    new_weekly_df["Date"] = pd.to_datetime(new_weekly_df["Date"])

    existing_df = existing_df[~existing_df["Date"].isin(new_weekly_df["Date"])]
    combined_df = pd.concat([existing_df, new_weekly_df], ignore_index=True)
    combined_df = combined_df.sort_values("Date").reset_index(drop=True)
    return combined_df


# -----------------------------------------------------------------------------
# Streamlit session-state helpers
# -----------------------------------------------------------------------------
def initialize_session_state():
    """
    Session state keys used on this tab:
    - forecast_initialized[store]: has the baseline forecast been run?
    - current_week[store]: next week to suggest on the slider.
    - uploaded_weeks[store]: weeks we have already processed.
    - forecast_history[store]: list of runs (Initial, Week 36, Week 37, ...)
    """
    if "forecast_initialized" not in st.session_state:
        st.session_state.forecast_initialized = {}
    if "current_week" not in st.session_state:
        st.session_state.current_week = {}
    if "uploaded_weeks" not in st.session_state:
        st.session_state.uploaded_weeks = {}
    if "forecast_history" not in st.session_state:
        st.session_state.forecast_history = {}


# -----------------------------------------------------------------------------
# File IO for forecast outputs
# -----------------------------------------------------------------------------
def save_forecast_output(store_name: str, output_data: dict, postfix: str = "") -> Path:
    """
    Save a forecast run to JSON so we can reload and compare later.
    postfix:
        "O"       -> Initial baseline
        "W36"     -> Week 36 re-forecast, etc.
    """
    file_name = FORECAST_DATA_FILE_NAMES[store_name]
    if postfix:
        file_name = file_name.replace(".json", f"_{postfix}.json")
    output_path = Path(FORECAST_DATA_FOLDER, file_name)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w") as f:
        json.dump(output_data, f, indent=4, default=str)

    return output_path


def load_forecast_output(store_name: str, postfix: str = ""):
    """
    Load a previous forecast run for the given store and postfix.
    """
    file_name = FORECAST_DATA_FILE_NAMES[store_name]
    if postfix:
        file_name = file_name.replace(".json", f"_{postfix}.json")
    output_path = Path(FORECAST_DATA_FOLDER, file_name)
    if output_path.exists():
        with open(output_path, "r") as f:
            return json.load(f)
    return None


# -----------------------------------------------------------------------------
# Data loading & validation
# -----------------------------------------------------------------------------
@st.cache_data(show_spinner=True)
def get_store_data(store_name: str, until_date: datetime | None = HISTORY_END_FOR_INITIAL):
    """
    Load historical sales & labour for a given store from all_stores.xlsx.

    Args:
        store_name: "Parramatta", "Castle Towers", "Double Bay"
        until_date: if provided, cut off data at this date (inclusive).
                    if None, return the full history for that store.
    """
    df_input = pd.read_excel("data/all_stores.xlsx")
    df_input["Date"] = pd.to_datetime(df_input["Date"])
    store_column_value = STORE_MAP_INPUTS[store_name]

    mask = df_input["Store"] == store_column_value
    if until_date is not None:
        mask &= df_input["Date"] <= until_date

    df_store = df_input.loc[mask, FORECAST_INPUT_REQUIRED_COLUMNS].copy()
    df_store.reset_index(drop=True, inplace=True)
    return df_store


def validate_input_data(df_store: pd.DataFrame) -> pd.DataFrame:
    """
    Ensure there are no missing dates in the input history.

    If a date is missing, we insert it with zeros for sales and hours so the
    forecasting engine sees a continuous timeline.
    """
    df_store["Date"] = pd.to_datetime(df_store["Date"])
    min_date = df_store["Date"].min()
    max_date = df_store["Date"].max()
    all_dates = pd.date_range(start=min_date, end=max_date)
    missing_dates = all_dates.difference(df_store["Date"])

    if not missing_dates.empty:
        missing_df = pd.DataFrame(
            [
                {
                    "Date": d,
                    "SalesActual": 0,
                    "SalesForecast": 0,
                    "HoursActual": 0,
                    "HoursForecast": 0,
                }
                for d in missing_dates
            ]
        )
        df_store = pd.concat([df_store, missing_df], ignore_index=True)
        df_store = df_store.sort_values("Date").reset_index(drop=True)

    print(
        f"Validated input data: {len(df_store)} records from "
        f"{min_date.date()} to {max_date.date()}"
    )
    return df_store


@st.cache_data(show_spinner=False)
def get_legacy_forecast_sigma(store_name: str):
    """
    Estimate the "noise" of the current legacy forecast.

    We take the historical error:
        legacy_error = SalesForecast - SalesActual
    and compute its standard deviation (σ).
    """
    df_hist = get_store_data(store_name, until_date=None)
    if df_hist is None or df_hist.empty:
        return None

    df_hist = validate_input_data(df_hist)
    errors = df_hist["SalesForecast"] - df_hist["SalesActual"]
    errors = errors.replace([np.inf, -np.inf], np.nan).dropna()

    if len(errors) == 0:
        return None

    return float(errors.std())


# -----------------------------------------------------------------------------
# Main tab render
# -----------------------------------------------------------------------------
def render():
    st.header("Re-Forecast Lab (Week-by-Week)")
    shrink_metric_cards()
    st.caption(
        "This view simulates a real trading environment. "
        "We freeze an initial baseline forecast, then re-forecast each week as new actual sales arrive. "
        "The goal is to show that our forecast is very **stable** over the next 12 weeks."
    )

    initialize_session_state()

    # Store selection (default: Parramatta)
    list_store_names = list(STORE_MAP_INPUTS.keys())
    store_name = st.selectbox(
        "Select Store",
        options=list_store_names,
        index=list_store_names.index("Parramatta"),
    )

    # Initialise per-store session keys
    if store_name not in st.session_state.forecast_initialized:
        # New simulation for this store → remove any left-over lab files
        cleanup_store_forecast_files(store_name)

        st.session_state.forecast_initialized[store_name] = False
        st.session_state.current_week[store_name] = FIRST_WEEK_NUMBER
        st.session_state.uploaded_weeks[store_name] = []
        st.session_state.forecast_history[store_name] = []

    # -------------------------------------------------------------------------
    # Summary cards at the top
    # -------------------------------------------------------------------------
    st.subheader("📊 Forecast Status")
    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric("Store", store_name)

    with col2:
        if st.session_state.forecast_initialized[store_name]:
            st.metric(
                "Next Week in Simulation",
                st.session_state.current_week[store_name],
            )
        else:
            st.metric("Status", "Baseline not yet run")

    with col3:
        weeks_uploaded = len(st.session_state.uploaded_weeks[store_name])
        st.metric("Weeks Simulated", weeks_uploaded)

    # -------------------------------------------------------------------------
    # Section 1 – Baseline (Initial) Forecast
    # -------------------------------------------------------------------------
    st.subheader("1️⃣ Initial Baseline Forecast")

    if not st.session_state.forecast_initialized[store_name]:
        st.info(
            f"First we build a baseline forecast using history up to "
            f"**{HISTORY_END_FOR_INITIAL.date()}** (end of Week 35). "
            f"The baseline forecast runs from **{INITIAL_FORECAST_START.date()}** "
            f"through to **{FINAL_FORECAST_DATE.date()}**."
        )

        try:
            df_store = get_store_data(store_name)
            if df_store.empty:
                st.error(f"No data found for store: {store_name}")
                return

            st.write(f"Historical records available for this baseline: **{len(df_store)} days**")
        except FileNotFoundError:
            st.error("Store data not found. Please ensure 'data/all_stores.xlsx' exists.")
            return

        if st.button("🚀 Run Initial Baseline Forecast", type="primary"):
            with st.spinner("Generating initial baseline forecast...( ~ 3 minutes)"):
                try:
                    df_store = validate_input_data(df_store)
                    qf = QuantumForecast(
                        intput_df=df_store,
                        forecast_start=INITIAL_FORECAST_START,
                        forecast_end=FINAL_FORECAST_DATE,
                        name=STORE_MAP_INPUTS[store_name],
                    )
                    qf.run()
                    output_data = qf.output_data

                    save_forecast_output(store_name, output_data, postfix="O")
                    st.success("✅ Baseline forecast completed and saved.")

                    st.session_state.forecast_initialized[store_name] = True
                    st.session_state.forecast_history[store_name].append(
                        {
                            "week": "Initial",
                            "forecast_start": output_data["ForecastStart"],
                            "forecast_end": output_data["ForecastEnd"],
                            "timestamp": datetime.now().isoformat(),
                        }
                    )

                    # Sample of forecast window only
                    with st.expander("📈 View Baseline Forecast Sample", expanded=True):
                        data_full = pd.DataFrame(output_data["Data"])
                        data_full["Date"] = pd.to_datetime(data_full["Date"]).dt.date
                        forecast_start_date = pd.to_datetime(
                            output_data["ForecastStart"]
                        ).date()
                        forecast_end_date = pd.to_datetime(
                            output_data["ForecastEnd"]
                        ).date()
                        df_forecast = data_full[
                            (data_full["Date"] >= forecast_start_date)
                            & (data_full["Date"] <= forecast_end_date)
                        ]
                        df_forecast = df_forecast[
                            [
                                "Date",
                                "Year",
                                "WoY",
                                "DayName",
                                "Intuitive_Forecast_Sales",
                                "RandomForest_Forecast",
                                "Hybrid_Forecast_Sales",
                                "Hybrid_Forecast_Labour",
                            ]
                        ]
                        st.dataframe(df_forecast, width='stretch')

                    st.info(
                        "You can now step through each week and see how little the forecast moves."
                    )

                except Exception as e:
                    st.error(f"Error running baseline forecast: {str(e)}")
                    import traceback

                    st.code(traceback.format_exc())
    else:
        st.success("✅ Baseline forecast already completed.")

        existing_forecast = load_forecast_output(store_name, postfix="O")
        if existing_forecast:
            st.info(
                f"Baseline forecast horizon: "
                f"{existing_forecast['ForecastStart']} → {existing_forecast['ForecastEnd']}"
            )

    # -------------------------------------------------------------------------
    # Section 2 – Weekly re-forecast with additional actuals
    # -------------------------------------------------------------------------
    if st.session_state.forecast_initialized[store_name]:
        st.subheader(
            f"2️⃣ Re-run Forecast Week-by-Week "
            f"({FIRST_WEEK_NUMBER}–{MAX_ACTUAL_WEEK}) – using cumulative actuals"
        )

        st.info(
            "Each step adds **one more week of actual sales** into the training data, "
            "then re-runs the forecast over the same horizon. "
            "This lets us see how much the forecast path drifts as new information arrives."
        )

        selected_week = st.slider(
            "Select Week to Include in Training",
            min_value=FIRST_WEEK_NUMBER,
            max_value=MAX_ACTUAL_WEEK,
            value=st.session_state.current_week[store_name],
            step=1,
            help="Forecast will use actual data up to the end of the selected week.",
        )

        week_start, week_end = get_week_dates(selected_week)
        st.write(
            f"**Selected Week {selected_week}:** "
            f"{week_start.strftime('%Y-%m-%d')} to {week_end.strftime('%Y-%m-%d')}"
        )

        if st.session_state.uploaded_weeks[store_name]:
            st.write(
                "Weeks already simulated: "
                + ", ".join(map(str, st.session_state.uploaded_weeks[store_name]))
            )

        if st.button(
            "🚀 Re-run forecast up to selected week",
            type="primary",
            key=f"run_week_{selected_week}",
        ):
            with st.spinner(
                f"Generating re-forecast using actual data through Week {selected_week}...this takes a few moments(~ 2 mins)"
            ):
                try:
                    # History up to the end of the selected week
                    df_store = get_store_data(store_name, until_date=week_end)
                    if df_store is None or df_store.empty:
                        st.error(f"No data found for store: {store_name}")
                        return

                    df_store = validate_input_data(df_store)
                    st.write(
                        f"Using **{len(df_store)} days** of actual history "
                        f"(through {week_end.strftime('%Y-%m-%d')})."
                    )

                    # Re-forecast over the SAME horizon as the baseline
                    qf = QuantumForecast(
                        intput_df=df_store,
                        forecast_start=INITIAL_FORECAST_START,
                        forecast_end=FINAL_FORECAST_DATE,
                        name=STORE_MAP_INPUTS[store_name],
                    )
                    qf.run()
                    output_data = qf.output_data

                    save_forecast_output(store_name, output_data, postfix=f"W{selected_week}")

                    if selected_week not in st.session_state.uploaded_weeks[store_name]:
                        st.session_state.uploaded_weeks[store_name].append(selected_week)
                        st.session_state.uploaded_weeks[store_name].sort()

                    st.session_state.current_week[store_name] = min(
                        selected_week + 1, MAX_ACTUAL_WEEK
                    )

                    history_exists = False
                    for record in st.session_state.forecast_history[store_name]:
                        if record["week"] == selected_week:
                            record["forecast_start"] = output_data["ForecastStart"]
                            record["forecast_end"] = output_data["ForecastEnd"]
                            record["timestamp"] = datetime.now().isoformat()
                            history_exists = True
                            break

                    if not history_exists:
                        st.session_state.forecast_history[store_name].append(
                            {
                                "week": selected_week,
                                "forecast_start": output_data["ForecastStart"],
                                "forecast_end": output_data["ForecastEnd"],
                                "timestamp": datetime.now().isoformat(),
                            }
                        )

                    st.success(
                        f"✅ Forecast with actual data through Week {selected_week} completed."
                    )

                    with st.expander("📈 View Latest Forecast Data"):
                        data_full = pd.DataFrame(output_data["Data"])
                        data_full["Date"] = pd.to_datetime(data_full["Date"]).dt.date
                        forecast_start_date_display = pd.to_datetime(
                            output_data["ForecastStart"]
                        ).date()
                        forecast_end_date_display = pd.to_datetime(
                            output_data["ForecastEnd"]
                        ).date()
                        df_forecast = data_full[
                            (data_full["Date"] >= forecast_start_date_display)
                            & (data_full["Date"] <= forecast_end_date_display)
                        ]
                        df_forecast = df_forecast[
                            [
                                "Date",
                                "Year",
                                "WoY",
                                "DayName",
                                "Intuitive_Forecast_Sales",
                                "RandomForest_Forecast",
                                "Hybrid_Forecast_Sales",
                                "Hybrid_Forecast_Labour",
                            ]
                        ]
                        st.dataframe(df_forecast, width='stretch')

                except Exception as e:
                    st.error(f"Error running re-forecast: {str(e)}")
                    import traceback

                    st.code(traceback.format_exc())

        st.markdown("---")

        # ---------------------------------------------------------------------
        # Section 3 – Forecast history table
        # ---------------------------------------------------------------------
        if st.session_state.forecast_history[store_name]:
            st.subheader("📜 Forecast Run History")
            history_df = pd.DataFrame(st.session_state.forecast_history[store_name])
            history_df["week"] = history_df["week"].astype(str)
            with st.expander("Show run history"):
                st.dataframe(history_df, width='stretch')

        # ---------------------------------------------------------------------
        # Section 4 – Sales forecast comparison & residuals with control bands
        # ---------------------------------------------------------------------
        st.subheader("Forecasted Sales Comparison & Stability")

        history_df = pd.DataFrame(st.session_state.forecast_history[store_name])
        if not history_df.empty:
            week_labels = history_df["week"].astype(str).tolist()
            week_labels_excluding_initial = [w for w in week_labels if w != "Initial"]

            selected_weeks = st.multiselect(
                "Select Weekly Re-Forecasts to Display",
                week_labels_excluding_initial,
                default=week_labels_excluding_initial,
            )

            # Helper to load a single run as a series
            def load_forecast_series(
                postfix: str, forecast_start: str, forecast_end: str, column_name: str
            ):
                data_full = load_forecast_output(store_name, postfix=postfix)
                if not data_full:
                    return None

                df_data = pd.DataFrame(data_full["Data"])
                df_data["Date"] = pd.to_datetime(df_data["Date"])
                df_filtered = df_data.loc[
                    (df_data["Date"] >= pd.to_datetime(forecast_start))
                    & (df_data["Date"] <= pd.to_datetime(forecast_end)),
                    ["Date", "Hybrid_Forecast_Sales", "SalesActual"],
                ].copy()
                df_filtered = df_filtered.rename(
                    columns={"Hybrid_Forecast_Sales": column_name}
                )
                return df_filtered

            # Load baseline
            data_initial = load_forecast_output(store_name, postfix="O")
            if data_initial:
                sales_chart_data = load_forecast_series(
                    postfix="O",
                    forecast_start=data_initial["ForecastStart"],
                    forecast_end=data_initial["ForecastEnd"],
                    column_name="Initial",
                )

                if sales_chart_data is not None:
                    sales_chart_data = sales_chart_data.drop(columns=["SalesActual"])

                    # Add each selected weekly run
                    for record in st.session_state.forecast_history[store_name]:
                        if str(record["week"]) not in selected_weeks:
                            continue
                        if record["week"] == "Initial":
                            continue

                        df_week = load_forecast_series(
                            postfix=f"W{record['week']}",
                            forecast_start=record["forecast_start"],
                            forecast_end=record["forecast_end"],
                            column_name=f"Week {record['week']}",
                        )
                        if df_week is not None:
                            df_week = df_week.drop(columns=["SalesActual"], errors="ignore")
                            sales_chart_data = sales_chart_data.merge(
                                df_week, on="Date", how="left"
                            )
                        else:
                            st.warning(
                                f"Forecast data for Week {record['week']} not found, skipping."
                            )

                    # Ensure proper ordering: Initial, then Week 36, Week 37, ...
                    sales_chart_data.set_index("Date", inplace=True)
                    sales_chart_data = sales_chart_data[~sales_chart_data.index.duplicated(keep="first")]
                    ordered_cols = ["Initial"] + sorted(
                        [c for c in sales_chart_data.columns if c != "Initial"]
                    )
                    sales_chart_data = sales_chart_data[ordered_cols]

                    # ------------------------ Sales Forecast Chart -----------------------
                    st.markdown("### 📈 Sales Forecast Paths")
                    fig_sales = go.Figure()
                    for col in ordered_cols:
                        fig_sales.add_trace(
                            go.Scatter(
                                x=sales_chart_data.index,
                                y=sales_chart_data[col],
                                mode="lines",
                                name=col,
                            )
                        )
                    fig_sales.update_layout(
                        xaxis_title="Date",
                        yaxis_title="Daily sales forecast",
                        hovermode="x unified",
                        legend_title="Forecast run",
                    )
                    st.plotly_chart(fig_sales, width='stretch')

                    # ---------------------- Residuals & Control Bands --------------------
                    st.markdown("### 📉 Forecast Drift vs Baseline")
                    st.caption(
                        "Each coloured line shows the difference between a weekly re-forecast "
                        "and the initial baseline forecast (Weekly – Initial)."
                    )

                    residuals_data = sales_chart_data.copy()
                    initial_forecast = residuals_data["Initial"].copy()

                    for col in ordered_cols:
                        residuals_data[col] = residuals_data[col] - initial_forecast

                    # Remove the 'Initial' zero line (we only care about drift)
                    residuals_data = residuals_data.drop(columns=["Initial"])

                    if len(residuals_data.columns) > 0:
                        # Stack residuals across all weeks to measure typical drift
                        drift_residuals = residuals_data.stack().dropna()
                        sigma_drift = float(drift_residuals.std()) if len(drift_residuals) > 0 else 0.0  # 1σ drift
                        two_sigma_drift = 2 * sigma_drift  # 2σ drift

                        legacy_sigma = get_legacy_forecast_sigma(store_name)  # 1σ error of existing process
                        two_sigma_legacy = 2 * legacy_sigma if legacy_sigma is not None else None  # 2σ error

                        # Use the baseline forecast to express sigmas as % of a typical day
                        mean_baseline_sales = float(initial_forecast.mean())
                        if mean_baseline_sales > 0:
                            drift_1sigma_pct = sigma_drift / mean_baseline_sales * 100
                            legacy_1sigma_pct = (
                                legacy_sigma / mean_baseline_sales * 100
                                if legacy_sigma is not None
                                else None
                            )
                            legacy_2sigma_pct = (
                                two_sigma_legacy / mean_baseline_sales * 100
                                if two_sigma_legacy is not None
                                else None
                            )
                        else:
                            drift_1sigma_pct = legacy_1sigma_pct = legacy_2sigma_pct = None

                        x_vals = residuals_data.index

                        fig_resid = go.Figure()

                        # Legacy forecast error band (wide red band)
                        if two_sigma_legacy is not None and two_sigma_legacy > 0:
                            fig_resid.add_trace(
                                go.Scatter(
                                    x=x_vals,
                                    y=[two_sigma_legacy] * len(x_vals),
                                    mode="lines",
                                    line=dict(width=0),
                                    showlegend=False,
                                    hoverinfo="skip",
                                )
                            )
                            fig_resid.add_trace(
                                go.Scatter(
                                    x=x_vals,
                                    y=[-two_sigma_legacy] * len(x_vals),
                                    mode="lines",
                                    fill="tonexty",
                                    line=dict(width=0),
                                    name="Current forecast ±2σ",
                                    hoverinfo="skip",
                                    fillcolor="rgba(255, 0, 0, 0.08)",
                                )
                            )

                        # Our forecast drift band (narrow green band)
                        if two_sigma_drift > 0:
                            fig_resid.add_trace(
                                go.Scatter(
                                    x=x_vals,
                                    y=[two_sigma_drift] * len(x_vals),
                                    mode="lines",
                                    line=dict(width=0),
                                    showlegend=False,
                                    hoverinfo="skip",
                                )
                            )
                            fig_resid.add_trace(
                                go.Scatter(
                                    x=x_vals,
                                    y=[-two_sigma_drift] * len(x_vals),
                                    mode="lines",
                                    fill="tonexty",
                                    line=dict(width=0),
                                    name="Our forecast drift ±2σ",
                                    hoverinfo="skip",
                                    fillcolor="rgba(0, 128, 0, 0.16)",
                                )
                            )

                        # Residual lines for each weekly run
                        for col in residuals_data.columns:
                            fig_resid.add_trace(
                                go.Scatter(
                                    x=x_vals,
                                    y=residuals_data[col],
                                    mode="lines",
                                    name=str(col),
                                    line=dict(width=1),
                                )
                            )

                        fig_resid.update_layout(
                            xaxis_title="Date",
                            yaxis_title="Difference vs baseline forecast",
                            hovermode="x unified",
                            legend_title="Run / Control band",
                        )
                        st.plotly_chart(fig_resid, width='stretch')

                        st.markdown(
                            "- **Coloured lines** = how much each weekly run moves versus the baseline.\n"
                            "- **Green band** = typical movement of our forecast (±2 standard deviations).\n"
                            "- **Red band** = typical error range of the current forecasting process.\n"
                            "If our lines sit tightly inside the green band – and the green band is much "
                            "narrower than the red band – it shows that our forecast is both **stable** "
                            "and **far more accurate** than the status quo."
                        )

                        # ---------------------- Summary metrics in an expander -------------
                        with st.expander("📊 Residual & Drift Summary"):

                            # High-level drift stats
                            if len(drift_residuals) > 0:
                                max_abs_drift = float(drift_residuals.abs().max())
                                avg_abs_drift = float(drift_residuals.abs().mean())
                            else:
                                max_abs_drift = avg_abs_drift = 0.0

                            col_a, col_b, col_c = st.columns(3)

                            col_a.metric(
                                "Max daily drift vs baseline",
                                f"{max_abs_drift:,.0f}",
                            )

                            col_b.metric(
                                "Our drift (1σ ≈ 68% of days)",
                                f"±{sigma_drift:,.0f}",
                                help="Typical day-to-day movement of our forecast when we re-run it each week.",
                            )

                            if legacy_sigma is not None:
                                col_c.metric(
                                    "Existing forecast error (2σ ≈ 95% of days)",
                                    f"±{two_sigma_legacy:,.0f}",
                                    help=(
                                        "Approximate two-sigma daily error range of the current "
                                        "forecasting process (about 95% of daily errors fall inside this band)."
                                    ),
                                )

                            # Short narrative under the cards
                            if (
                                    legacy_sigma is not None
                                    and drift_1sigma_pct is not None
                                    and legacy_1sigma_pct is not None
                                    and legacy_2sigma_pct is not None
                                    and legacy_sigma > 0
                            ):
                                ratio = sigma_drift / legacy_sigma
                                st.markdown(
                                    f"""
                                    **How to read these numbers**

                                    - Our forecast drift **1σ**: ±{sigma_drift:,.0f} per day "
                                      f"(≈ {drift_1sigma_pct:.1f}% of a typical day’s sales).
                                    - Existing process error **1σ**: ±{legacy_sigma:,.0f} per day "
                                      f"(≈ {legacy_1sigma_pct:.1f}% of sales).
                                    - Existing process error **2σ**: ±{two_sigma_legacy:,.0f} per day "
                                      f"(≈ {legacy_2sigma_pct:.1f}% of sales) – this is the wide red band above.
                                    - Our re-forecasts move inside a band that is only about "
                                      f"**{ratio * 100:.1f}% of the current 1σ error**.
                                    """
                                )

                            # Table of RMSE & average % difference by run
                            st.markdown("**Forecast accuracy vs baseline (by run)**")

                            metrics_data = []
                            for col in residuals_data.columns:
                                # Residuals for this run (Weekly - Initial)
                                series_resid = residuals_data[col].dropna()
                                if len(series_resid) == 0:
                                    continue

                                # RMSE of the drift for this run
                                rmse = float(np.sqrt((series_resid ** 2).mean()))

                                # Grab the matching baseline values on the same dates
                                base_initial = initial_forecast.loc[series_resid.index]

                                # Build a small table using raw values (ignore index to avoid
                                # any duplicate-label reindex issues)
                                df_pair = pd.DataFrame(
                                    {
                                        "residual": series_resid.to_numpy(),
                                        "initial": base_initial.to_numpy(),
                                    }
                                )

                                # Clean up and avoid divide-by-zero
                                df_pair = df_pair.replace([np.inf, -np.inf], np.nan).dropna()
                                df_pair = df_pair[df_pair["initial"] != 0]

                                if df_pair.empty:
                                    pct_diff = None
                                else:
                                    pct_diff = float(
                                        ((df_pair["residual"] / df_pair["initial"]) * 100).mean()
                                    )

                                metrics_data.append(
                                    {
                                        "Week / Run": col,
                                        "RMSE vs baseline": round(rmse, 2),
                                        "Avg % difference": (
                                            round(pct_diff, 2) if pct_diff is not None else None
                                        ),
                                    }
                                )

                            metrics_df = pd.DataFrame(metrics_data)
                            st.dataframe(metrics_df, width='stretch')

                    else:
                        st.info("Run at least one weekly re-forecast to see residuals.")
                else:
                    st.warning("Could not load baseline forecast data.")
            else:
                st.warning("Baseline forecast not found on disk. Please re-run the initial step.")
        else:
            st.info("No forecast runs available yet. Start with the baseline, then add weeks.")

        # ---------------------------------------------------------------------
        # Advanced options – reset this store
        # ---------------------------------------------------------------------
        with st.expander("⚙️ Advanced Options"):
            if st.button("🔄 Reset Forecast Simulation for This Store", type="secondary"):
                # Delete lab files for this store
                cleanup_store_forecast_files(store_name)

                # Reset in-memory state
                st.session_state.forecast_initialized[store_name] = False
                st.session_state.current_week[store_name] = FIRST_WEEK_NUMBER
                st.session_state.uploaded_weeks[store_name] = []
                st.session_state.forecast_history[store_name] = []

                st.success("Store simulation reset and temporary forecast files cleaned up.")
                st.rerun()

    # If baseline not yet run, we simply stop after section 1
    return
